import { Router } from "express";
import { requireAuth } from "../middlewares/auth";
import {
  getEntriesForUser,
  createEntry,
  updateEntry,
  deleteEntry,
} from "../adapters/repositories/entryRepository";
import { updateStreak } from "../adapters/repositories/userRepository";
import { getCategoriesForUser } from "../adapters/repositories/budgetRepository";

function getWeekBounds(dateStr: string): { weekStart: string; weekEnd: string } {
  const d = new Date(dateStr + "T12:00:00Z");
  const dayOfWeek = d.getUTCDay();
  const ws = new Date(d);
  ws.setUTCDate(d.getUTCDate() - dayOfWeek);
  const we = new Date(ws);
  we.setUTCDate(ws.getUTCDate() + 6);
  return {
    weekStart: ws.toISOString().split("T")[0]!,
    weekEnd: we.toISOString().split("T")[0]!,
  };
}

const router = Router();

function formatEntry(e: {
  id: string;
  userId: string;
  categoryId: string;
  categoryName: string | null;
  categoryIcon: string | null;
  categoryColour: string | null;
  amount: string;
  description: string | null;
  inputMethod: string;
  entryDate: string;
  isRecurring: boolean;
  recurringDay: number | null;
  isAutoGenerated: boolean;
  createdAt: Date;
}) {
  return {
    id: e.id,
    userId: e.userId,
    categoryId: e.categoryId,
    categoryName: e.categoryName,
    categoryIcon: e.categoryIcon,
    categoryColour: e.categoryColour,
    amount: Number(e.amount),
    description: e.description,
    inputMethod: e.inputMethod,
    entryDate: e.entryDate,
    isRecurring: e.isRecurring,
    recurringDay: e.recurringDay,
    isAutoGenerated: e.isAutoGenerated,
    createdAt: e.createdAt.toISOString(),
  };
}

router.get("/", requireAuth, async (req, res) => {
  const { startDate, endDate, categoryId } = req.query;
  const entries = await getEntriesForUser(req.user!.userId, {
    startDate: startDate as string | undefined,
    endDate: endDate as string | undefined,
    categoryId: categoryId as string | undefined,
  });
  res.json(entries.map(formatEntry));
});

router.post("/", requireAuth, async (req, res) => {
  const { categoryId, amount, description, inputMethod, entryDate, isRecurring } = req.body;

  if (!categoryId || !amount || !inputMethod) {
    res.status(400).json({ error: "categoryId, amount, and inputMethod are required" });
    return;
  }

  const today = new Date().toISOString().split("T")[0]!;
  const dateToUse = (entryDate ?? today) as string;
  const parsedDate = dateToUse.includes("T") ? dateToUse.split("T")[0]! : dateToUse;

  const recurringFlag = !!isRecurring;
  const recurringDay = recurringFlag ? parseInt(parsedDate.split("-")[2]!, 10) : null;

  const entry = await createEntry({
    userId: req.user!.userId,
    categoryId,
    amount: Number(amount),
    description: description ?? null,
    inputMethod,
    entryDate: parsedDate,
    isRecurring: recurringFlag,
    recurringDay,
    isAutoGenerated: false,
  });

  // Update streak for today (non-blocking, don't fail the request)
  updateStreak(req.user!.userId, today).catch(() => {});

  const [entries, categories] = await Promise.all([
    getEntriesForUser(req.user!.userId, { startDate: entry.entryDate, endDate: entry.entryDate }),
    getCategoriesForUser(req.user!.userId),
  ]);
  const full = entries.find((e) => e.id === entry.id);

  // Overspend check: is this category over its weekly budget now?
  const { weekStart, weekEnd } = getWeekBounds(parsedDate);
  const weekEntries = await getEntriesForUser(req.user!.userId, { startDate: weekStart, endDate: weekEnd });

  let overspend: null | {
    categoryId: string;
    categoryName: string;
    overspendAmount: number;
    weekStart: string;
    entryId: string;
    otherCategories: Array<{ id: string; name: string; remaining: number }>;
  } = null;

  const thisCat = categories.find((c) => c.id === categoryId);
  if (thisCat) {
    const weeklyBudget = Number(thisCat.monthlyBudget) / 4.33;
    const catSpend: Record<string, number> = {};
    for (const e of weekEntries) {
      catSpend[e.categoryId] = (catSpend[e.categoryId] ?? 0) + Number(e.amount);
    }
    const totalSpentInCat = catSpend[categoryId] ?? 0;

    if (weeklyBudget > 0 && totalSpentInCat > weeklyBudget) {
      const overspendAmount = Math.round((totalSpentInCat - weeklyBudget) * 100) / 100;
      const otherCats = categories
        .filter((c) => c.id !== categoryId)
        .map((c) => {
          const spent = catSpend[c.id] ?? 0;
          const wb = Number(c.monthlyBudget) / 4.33;
          const remaining = Math.max(0, Math.round((wb - spent) * 100) / 100);
          return { id: c.id, name: c.name, remaining };
        })
        .filter((c) => c.remaining > 0)
        .sort((a, b) => b.remaining - a.remaining);

      overspend = {
        categoryId: thisCat.id,
        categoryName: thisCat.name,
        overspendAmount,
        weekStart,
        entryId: entry.id,
        otherCategories: otherCats,
      };
    }
  }

  const responseEntry = full
    ? formatEntry(full)
    : {
        id: entry.id,
        userId: entry.userId,
        categoryId: entry.categoryId,
        categoryName: null,
        categoryIcon: null,
        categoryColour: null,
        amount: Number(entry.amount),
        description: entry.description,
        inputMethod: entry.inputMethod,
        entryDate: entry.entryDate,
        isRecurring: entry.isRecurring,
        recurringDay: entry.recurringDay,
        isAutoGenerated: entry.isAutoGenerated,
        createdAt: entry.createdAt.toISOString(),
      };

  res.status(201).json({ ...responseEntry, overspend });
});

router.patch("/:id", requireAuth, async (req, res) => {
  const { id } = req.params;
  const { amount, description } = req.body;

  if (!id) {
    res.status(400).json({ error: "Entry ID is required" });
    return;
  }

  await updateEntry(id, req.user!.userId, {
    ...(amount != null ? { amount: Number(amount) } : {}),
    ...(description !== undefined ? { description: description ?? null } : {}),
  });

  const entries = await getEntriesForUser(req.user!.userId);
  const updated = entries.find((e) => e.id === id);
  if (!updated) {
    res.status(404).json({ error: "Entry not found" });
    return;
  }

  res.json(formatEntry(updated));
});

router.delete("/:id", requireAuth, async (req, res) => {
  await deleteEntry(req.params["id"]!, req.user!.userId);
  res.json({ success: true, message: "Entry deleted" });
});

export default router;
