// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding-welcome/FullBleed.tsx": () => import("../components/mockups/onboarding-welcome/FullBleed.tsx"),
  "./components/mockups/onboarding-welcome/PersonaPeek.tsx": () => import("../components/mockups/onboarding-welcome/PersonaPeek.tsx"),
  "./components/mockups/onboarding-welcome/WordsOnly.tsx": () => import("../components/mockups/onboarding-welcome/WordsOnly.tsx")
};
